# Generated by Django 3.0.8 on 2020-07-25 14:50

from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('thumbnail', models.URLField()),
                ('content', mdeditor.fields.MDTextField()),
                ('publish_time', models.DateTimeField(auto_now_add=True)),
                ('show_on_index_or_not', models.BooleanField(default=False, verbose_name='是否在首页显示')),
                ('show_on_top_index_or_not', models.BooleanField(default=False, verbose_name='是否在轮播显示')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CybersCometBlog.Category')),
                ('tag', models.ManyToManyField(to='CybersCometBlog.Tag')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
    ]
