# Generated by Django 3.0.8 on 2020-07-25 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CybersCometBlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '分类', 'verbose_name_plural': '分类'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '标签', 'verbose_name_plural': '标签'},
        ),
    ]
