# Generated by Django 3.0.8 on 2020-07-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CybersCometBlog', '0003_auto_20200726_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='main_photo_link',
            field=models.CharField(default='None', max_length=200, verbose_name='主图片地址'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(blank=True, to='CybersCometBlog.Tag', verbose_name='标签'),
        ),
    ]
