# Generated by Django 3.0.8 on 2020-07-27 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CybersCometBlog', '0004_auto_20200726_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_id',
            field=models.CharField(default='0', max_length=10, verbose_name='文章ID'),
        ),
    ]
