# Generated by Django 3.0.8 on 2020-07-27 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CybersCometBlog', '0005_article_article_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_id',
        ),
    ]
