# Generated by Django 3.0.8 on 2020-07-27 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CybersCometBlog', '0006_remove_article_article_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100, verbose_name='内容')),
                ('publish_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('publisher_name', models.CharField(default='路过的小同志', max_length=50, verbose_name='评论者姓名')),
            ],
        ),
    ]
