# Generated by Django 3.0.8 on 2020-07-27 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CybersCometBlog', '0007_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
        migrations.AddField(
            model_name='article',
            name='comment',
            field=models.ManyToManyField(blank=True, to='CybersCometBlog.Comment', verbose_name='评论'),
        ),
        migrations.AddField(
            model_name='comment',
            name='reply_article_id',
            field=models.CharField(default='0', max_length=20, verbose_name='回复文章ID'),
        ),
    ]
