# Generated by Django 3.0.8 on 2020-07-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CybersCometBlog', '0008_auto_20200727_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
