# Generated by Django 3.0.8 on 2020-07-27 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CybersCometBlog', '0009_commentform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentForm',
        ),
    ]
