# Generated by Django 3.0.8 on 2020-07-29 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CybersCometBlog', '0011_notice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'verbose_name': '通知', 'verbose_name_plural': '通知'},
        ),
    ]
