# Generated by Django 3.0.8 on 2020-07-30 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CybersCometBlog', '0012_auto_20200729_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='内容')),
                ('email', models.EmailField(default='example@xxx.com', max_length=40, verbose_name='邮箱地址')),
                ('phone', models.CharField(default='10086', max_length=20, verbose_name='电话号码')),
                ('content', models.CharField(max_length=150, verbose_name='内容')),
                ('publish_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('show_on_index_or_not', models.BooleanField(default=True, verbose_name='是否在首页显示')),
            ],
            options={
                'verbose_name': '微言',
                'verbose_name_plural': '微言',
            },
        ),
    ]
