# Generated by Django 3.0.8 on 2020-07-30 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CybersCometBlog', '0013_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=100, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(max_length=150, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='content',
            field=models.TextField(max_length=100, verbose_name='内容'),
        ),
    ]
