# Generated by Django 3.0.8 on 2020-07-30 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CybersCometBlog', '0014_auto_20200730_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(default='路过的小同志', max_length=50, verbose_name='内容'),
        ),
    ]
